package model;
// Generated Mar 18, 2018 7:17:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EntranceExit generated by hbm2java
 */
public class EntranceExit  implements java.io.Serializable {


     private Integer identranceExit;
     private String name;
     private Set ticketsForEnd = new HashSet(0);
     private Set ticketsForStart = new HashSet(0);

    public EntranceExit() {
    }

    public EntranceExit(String name, Set ticketsForEnd, Set ticketsForStart) {
       this.name = name;
       this.ticketsForEnd = ticketsForEnd;
       this.ticketsForStart = ticketsForStart;
    }
   
    public Integer getIdentranceExit() {
        return this.identranceExit;
    }
    
    public void setIdentranceExit(Integer identranceExit) {
        this.identranceExit = identranceExit;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTicketsForEnd() {
        return this.ticketsForEnd;
    }
    
    public void setTicketsForEnd(Set ticketsForEnd) {
        this.ticketsForEnd = ticketsForEnd;
    }
    public Set getTicketsForStart() {
        return this.ticketsForStart;
    }
    
    public void setTicketsForStart(Set ticketsForStart) {
        this.ticketsForStart = ticketsForStart;
    }




}


