package model;
// Generated Mar 17, 2018 1:36:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fine generated by hbm2java
 */
public class Fine  implements java.io.Serializable {


     private Integer idfine;
     private String finecol;
     private Set tickets = new HashSet(0);

    public Fine() {
    }

    public Fine(String finecol, Set tickets) {
       this.finecol = finecol;
       this.tickets = tickets;
    }
   
    public Integer getIdfine() {
        return this.idfine;
    }
    
    public void setIdfine(Integer idfine) {
        this.idfine = idfine;
    }
    public String getFinecol() {
        return this.finecol;
    }
    
    public void setFinecol(String finecol) {
        this.finecol = finecol;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


