package model;
// Generated Mar 17, 2018 1:36:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private Integer idvehicle;
     private String number;
     private Set tickets = new HashSet(0);

    public Vehicle() {
    }

	
    public Vehicle(String number) {
        this.number = number;
    }
    public Vehicle(String number, Set tickets) {
       this.number = number;
       this.tickets = tickets;
    }
   
    public Integer getIdvehicle() {
        return this.idvehicle;
    }
    
    public void setIdvehicle(Integer idvehicle) {
        this.idvehicle = idvehicle;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


