package model;
// Generated Mar 18, 2018 7:40:05 AM by Hibernate Tools 4.3.1



/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private Integer idvehicle;
     private Ticket ticket;
     private String number;

    public Vehicle() {
    }

    public Vehicle(Ticket ticket, String number) {
       this.ticket = ticket;
       this.number = number;
    }
   
    public Integer getIdvehicle() {
        return this.idvehicle;
    }
    
    public void setIdvehicle(Integer idvehicle) {
        this.idvehicle = idvehicle;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }




}


