package model.db;
// Generated 21-May-2017 23:55:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver  implements java.io.Serializable {


     private Integer iddriver;
     private Status status;
     private String name;
     private String licenceNumber;
     private Set payments = new HashSet(0);
     private Set tickets = new HashSet(0);

    public Driver() {
    }

	
    public Driver(Status status) {
        this.status = status;
    }
    public Driver(Status status, String name, String licenceNumber, Set payments, Set tickets) {
       this.status = status;
       this.name = name;
       this.licenceNumber = licenceNumber;
       this.payments = payments;
       this.tickets = tickets;
    }
   
    public Integer getIddriver() {
        return this.iddriver;
    }
    
    public void setIddriver(Integer iddriver) {
        this.iddriver = iddriver;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLicenceNumber() {
        return this.licenceNumber;
    }
    
    public void setLicenceNumber(String licenceNumber) {
        this.licenceNumber = licenceNumber;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


