package model.db;
// Generated 21-May-2017 23:55:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fine generated by hbm2java
 */
public class Fine  implements java.io.Serializable {


     private Integer idfine;
     private String description;
     private Double fine;
     private Set tickets = new HashSet(0);

    public Fine() {
    }

    public Fine(String description, Double fine, Set tickets) {
       this.description = description;
       this.fine = fine;
       this.tickets = tickets;
    }
   
    public Integer getIdfine() {
        return this.idfine;
    }
    
    public void setIdfine(Integer idfine) {
        this.idfine = idfine;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getFine() {
        return this.fine;
    }
    
    public void setFine(Double fine) {
        this.fine = fine;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


