package model.db;
// Generated 21-May-2017 23:55:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer idpayment;
     private Driver driver;
     private Ticket ticket;
     private Date paymentDate;

    public Payment() {
    }

	
    public Payment(Ticket ticket) {
        this.ticket = ticket;
    }
    public Payment(Driver driver, Ticket ticket, Date paymentDate) {
       this.driver = driver;
       this.ticket = ticket;
       this.paymentDate = paymentDate;
    }
   
    public Integer getIdpayment() {
        return this.idpayment;
    }
    
    public void setIdpayment(Integer idpayment) {
        this.idpayment = idpayment;
    }
    public Driver getDriver() {
        return this.driver;
    }
    
    public void setDriver(Driver driver) {
        this.driver = driver;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }




}


