package model.db;
// Generated 21-May-2017 23:55:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer idstatus;
     private String status;
     private Set drivers = new HashSet(0);
     private Set tickets = new HashSet(0);
     private Set users = new HashSet(0);

    public Status() {
    }

    public Status(String status, Set drivers, Set tickets, Set users) {
       this.status = status;
       this.drivers = drivers;
       this.tickets = tickets;
       this.users = users;
    }
   
    public Integer getIdstatus() {
        return this.idstatus;
    }
    
    public void setIdstatus(Integer idstatus) {
        this.idstatus = idstatus;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getDrivers() {
        return this.drivers;
    }
    
    public void setDrivers(Set drivers) {
        this.drivers = drivers;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


