package model.db;
// Generated 21-May-2017 23:55:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private Integer idticket;
     private Driver driver;
     private PoliceStation policeStation;
     private Status status;
     private TrafficOfficer trafficOfficer;
     private Date issueDate;
     private String drivingLicenceIddrivingLicence;
     private Double totalAmount;
     private String longitude;
     private String latitude;
     private String vechicleNumber;
     private Set payments = new HashSet(0);
     private Set fines = new HashSet(0);

    public Ticket() {
    }

	
    public Ticket(Driver driver, PoliceStation policeStation, Status status, TrafficOfficer trafficOfficer, String drivingLicenceIddrivingLicence) {
        this.driver = driver;
        this.policeStation = policeStation;
        this.status = status;
        this.trafficOfficer = trafficOfficer;
        this.drivingLicenceIddrivingLicence = drivingLicenceIddrivingLicence;
    }
    public Ticket(Driver driver, PoliceStation policeStation, Status status, TrafficOfficer trafficOfficer, Date issueDate, String drivingLicenceIddrivingLicence, Double totalAmount, String longitude, String latitude, String vechicleNumber, Set payments, Set fines) {
       this.driver = driver;
       this.policeStation = policeStation;
       this.status = status;
       this.trafficOfficer = trafficOfficer;
       this.issueDate = issueDate;
       this.drivingLicenceIddrivingLicence = drivingLicenceIddrivingLicence;
       this.totalAmount = totalAmount;
       this.longitude = longitude;
       this.latitude = latitude;
       this.vechicleNumber = vechicleNumber;
       this.payments = payments;
       this.fines = fines;
    }
   
    public Integer getIdticket() {
        return this.idticket;
    }
    
    public void setIdticket(Integer idticket) {
        this.idticket = idticket;
    }
    public Driver getDriver() {
        return this.driver;
    }
    
    public void setDriver(Driver driver) {
        this.driver = driver;
    }
    public PoliceStation getPoliceStation() {
        return this.policeStation;
    }
    
    public void setPoliceStation(PoliceStation policeStation) {
        this.policeStation = policeStation;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public TrafficOfficer getTrafficOfficer() {
        return this.trafficOfficer;
    }
    
    public void setTrafficOfficer(TrafficOfficer trafficOfficer) {
        this.trafficOfficer = trafficOfficer;
    }
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }
    public String getDrivingLicenceIddrivingLicence() {
        return this.drivingLicenceIddrivingLicence;
    }
    
    public void setDrivingLicenceIddrivingLicence(String drivingLicenceIddrivingLicence) {
        this.drivingLicenceIddrivingLicence = drivingLicenceIddrivingLicence;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getVechicleNumber() {
        return this.vechicleNumber;
    }
    
    public void setVechicleNumber(String vechicleNumber) {
        this.vechicleNumber = vechicleNumber;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }
    public Set getFines() {
        return this.fines;
    }
    
    public void setFines(Set fines) {
        this.fines = fines;
    }




}


