package model.db;
// Generated 21-May-2017 23:55:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TrafficOfficer generated by hbm2java
 */
public class TrafficOfficer  implements java.io.Serializable {


     private int userIdusers;
     private PoliceStation policeStation;
     private User user;
     private String officerId;
     private String name;
     private Set tickets = new HashSet(0);
     private Set workingHistories = new HashSet(0);

    public TrafficOfficer() {
    }

	
    public TrafficOfficer(PoliceStation policeStation, User user) {
        this.policeStation = policeStation;
        this.user = user;
    }
    public TrafficOfficer(PoliceStation policeStation, User user, String officerId, String name, Set tickets, Set workingHistories) {
       this.policeStation = policeStation;
       this.user = user;
       this.officerId = officerId;
       this.name = name;
       this.tickets = tickets;
       this.workingHistories = workingHistories;
    }
   
    public int getUserIdusers() {
        return this.userIdusers;
    }
    
    public void setUserIdusers(int userIdusers) {
        this.userIdusers = userIdusers;
    }
    public PoliceStation getPoliceStation() {
        return this.policeStation;
    }
    
    public void setPoliceStation(PoliceStation policeStation) {
        this.policeStation = policeStation;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getOfficerId() {
        return this.officerId;
    }
    
    public void setOfficerId(String officerId) {
        this.officerId = officerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }
    public Set getWorkingHistories() {
        return this.workingHistories;
    }
    
    public void setWorkingHistories(Set workingHistories) {
        this.workingHistories = workingHistories;
    }




}


