package model.db;
// Generated 21-May-2017 23:55:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idusers;
     private Status status;
     private UserType userType;
     private String username;
     private String password;
     private TrafficOfficer trafficOfficer;
     private PoliceStation policeStation;
     private Set userLogins = new HashSet(0);

    public User() {
    }

	
    public User(Status status, UserType userType) {
        this.status = status;
        this.userType = userType;
    }
    public User(Status status, UserType userType, String username, String password, TrafficOfficer trafficOfficer, PoliceStation policeStation, Set userLogins) {
       this.status = status;
       this.userType = userType;
       this.username = username;
       this.password = password;
       this.trafficOfficer = trafficOfficer;
       this.policeStation = policeStation;
       this.userLogins = userLogins;
    }
   
    public Integer getIdusers() {
        return this.idusers;
    }
    
    public void setIdusers(Integer idusers) {
        this.idusers = idusers;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public TrafficOfficer getTrafficOfficer() {
        return this.trafficOfficer;
    }
    
    public void setTrafficOfficer(TrafficOfficer trafficOfficer) {
        this.trafficOfficer = trafficOfficer;
    }
    public PoliceStation getPoliceStation() {
        return this.policeStation;
    }
    
    public void setPoliceStation(PoliceStation policeStation) {
        this.policeStation = policeStation;
    }
    public Set getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set userLogins) {
        this.userLogins = userLogins;
    }




}


